title: Albrecht Lab _C. elegans_ and Microfluidics Tools
lang: en
description: A series of software and hardware pages relating our experimental setups for microfluidics and neuroscience.

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
